### ISSUE TITLE
Angular 9 issues

### ISSUE THREAD

**Issue by ElderOrb** [josex2r/jQuery-SlotMachine#71] opened 2020-02-20 08:36 UTC
I'm trying to integrate jquery-slotmachine into Angular 9-based app, and it _nearly_ works, but for some reasons animation gets stuck in 'ng build --prod' (in all the browsers) or in 'ng serve' (in firefox)

Here is what I'm doing: 

slot-machine.component.html:

```
<!-- Slot machine example -->
<div id="casino" style="padding-top:50px;">
  <div class="content">
    <h1>Use the API</h1>

    <div>
      <div #casino1 id="casino1" class="slotMachine" style="margin-left: -65px;">
        <div class="slot slot1"></div>
        <div class="slot slot2"></div>
        <div class="slot slot3"></div>
        <div class="slot slot4"></div>
        <div class="slot slot5"></div>
        <div class="slot slot6"></div>
      </div>

      <div #casino2 id="casino2" class="slotMachine">
        <div class="slot slot1"></div>
        <div class="slot slot2"></div>
        <div class="slot slot3"></div>
        <div class="slot slot4"></div>
        <div class="slot slot5"></div>
        <div class="slot slot6"></div>
      </div>

      <div #casino3 id="casino3" class="slotMachine">
        <div class="slot slot1"></div>
        <div class="slot slot2"></div>
        <div class="slot slot3"></div>
        <div class="slot slot4"></div>
        <div class="slot slot5"></div>
        <div class="slot slot6"></div>
      </div>

      <div class="btn-group btn-group-justified" role="group">
        <button #casinoShuffle id="casinoShuffle" type="button" class="btn btn-primary btn-lg">Shuffle!</button>
        <button #casinoStop id="casinoStop" type="button" class="btn btn-primary btn-lg">Stop!</button>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-sm-10 col-md-5 offset-sm-1 offset-md-1">
        <pre><code id="codeBlock5"></code></pre>
      </div>

      <div class="col-sm-10 col-md-5 offset-sm-1 offset-md-0">
        <pre><code id="codeBlock6"></code></pre>
      </div>
    </div>
  </div>
</div>
```

slot-machine.component.ts: 

```
import { Component, OnInit, ViewEncapsulation, AfterViewInit, ViewChild, ElementRef } from '@angular/core';
import 'jquery/dist/jquery.min.js';
import SlotMachine from 'jquery-slotmachine/lib/slot-machine.js';

@Component({
  selector: 'app-slot-machine',
  templateUrl: './slot-machine.component.html',
  encapsulation: ViewEncapsulation.ShadowDom,
  styleUrls: ['./slot-machine.component.scss']
})
export class SlotMachineComponent implements OnInit, AfterViewInit {

  @ViewChild('casinoShuffle') casinoShuffle: ElementRef;
  @ViewChild('casinoStop') casinoStop: ElementRef;

  @ViewChild('casino1') casino1: ElementRef;
  @ViewChild('casino2') casino2: ElementRef;
  @ViewChild('casino3') casino3: ElementRef;

  ngAfterViewInit(): void {

    let count = 0;
    const btnShuffle = this.casinoShuffle.nativeElement;
    const btnStop = this.casinoStop.nativeElement;
    const casino1 = this.casino1.nativeElement;
    const casino2 = this.casino2.nativeElement;
    const casino3 = this.casino3.nativeElement;
    const mCasino1 = new SlotMachine(casino1, {
      active: 0,
      delay: 500
    });
    const mCasino2 = new SlotMachine(casino2, {
      active: 1,
      delay: 500
    });
    const mCasino3 = new SlotMachine(casino3, {
      active: 2,
      delay: 500
    });

    btnShuffle.addEventListener('click', () => {
      count = 3;
      mCasino1.shuffle(9999);
      mCasino2.shuffle(9999);
      mCasino3.shuffle(9999);
    });

    btnStop.addEventListener('click', () => {
      switch(count) {
        case 3:
          mCasino1.stop();
          break;
        case 2:
          mCasino2.stop();
          break;
        case 1:
          mCasino3.stop();
          break;
      }
      count--;
    });
  }

  constructor() { }

  ngOnInit(): void {

  }

}

```

slot-machine.component.scss: 

```
@import '../../../../node_modules/jquery-slotmachine/styles/style.css';

/*
 * jQuery Slot Machine v4.0.0
 * https://github.com/josex2r/jQuery-SlotMachineundefined
 *
 * Copyright 2014 Jose Luis Represa
 * Released under the MIT license
 */
 .slotMachineNoTransition {
  -webkit-transition: none !important;
  -o-transition: none !important;
  transition: none !important;
}

.slotMachineBlurFast {
  -webkit-filter: blur(5px);
  filter: blur(5px);
}

.slotMachineBlurMedium {
  -webkit-filter: blur(3px);
  filter: blur(3px);
}

.slotMachineBlurSlow {
  -webkit-filter: blur(2px);
  filter: blur(2px);
}

.slotMachineBlurTurtle {
  -webkit-filter: blur(1px);
  filter: blur(1px);
}

/*
.slotMachineGradient {
  -webkit-mask-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%, rgba(0,0,0,0)), color-stop(25%, rgba(0,0,0,1)), color-stop(75%, rgba(0,0,0,1)), color-stop(100%, rgba(0,0,0,0)) );
  -webkit-mask: url("data:image/svg+xml;utf8,<svg version="1.1" xmlns="http:// www.w3.org/2000/svg" width="0" height="0"><mask id="slotMachineFadeMask" maskUnits="objectBoundingBox" maskContentUnits="objectBoundingBox"><linearGradient id="slotMachineFadeGradient" gradientUnits="objectBoundingBox" x="0" y="0"><stop stop-color="white" stop-opacity="0" offset="0"></stop><stop stop-color="white" stop-opacity="1" offset="0.25"></stop><stop stop-color="white" stop-opacity="1" offset="0.75"></stop><stop stop-color="white" stop-opacity="0" offset="1"></stop></linearGradient><rect x="0" y="-1" width="1" height="1" transform="rotate(90)" fill="url(#slotMachineFadeMask)"></rect></mask></svg>#slotMachineFadeMask");
  mask: url("data:image/svg+xml;utf8,<svg version="1.1" xmlns="http:// www.w3.org/2000/svg" width="0" height="0"><mask id="slotMachineFadeMask" maskUnits="objectBoundingBox" maskContentUnits="objectBoundingBox"><linearGradient id="slotMachineFadeGradient" gradientUnits="objectBoundingBox" x="0" y="0"><stop stop-color="white" stop-opacity="0" offset="0"></stop><stop stop-color="white" stop-opacity="1" offset="0.25"></stop><stop stop-color="white" stop-opacity="1" offset="0.75"></stop><stop stop-color="white" stop-opacity="0" offset="1"></stop></linearGradient><rect x="0" y="-1" width="1" height="1" transform="rotate(90)" fill="url(#slotMachineFadeMask)"></rect></mask></svg>#slotMachineFadeMask");
}
*/

```

Any ideas what could go wrong?

**Comment by josex2r** [comment] 2020-02-20 10:19
Hi. Do you have an error stack or something similar?

Maybe you have conflicts with Babel or your JS-minifier, try not to import the minified file and delegate that job to your Angular bundler.

**Comment by ElderOrb** [comment] 2020-02-20 11:25
No errors, nothing at all. But further investigations showed the following: 

1. If I delay slot machine initialization (like wrapp all the code from ngAfterViewInit into timer(100).toPromise().then(.... )) - firefox start working for developer builds. 'ng build --prod' is still broken. 

2. If I set breakpoints inside _setBounds / shuffle (not sure which exactly, most likely just _setBounds is enough) - then it breaking even from debug builds of chromium. 

> try not to import the minified file and delegate that job to your Angular bundler.

you mean reference it inside angular.json instead of in component?

**Comment by ElderOrb** [comment] 2020-02-20 21:35
Okay, I've found that 'ng build --prod --optimization=false' seems to resolve the issue for production build, so looks like optimizer breaks functionality. Do you know how to exclude this particular js from optimization?

**Comment by ElderOrb** [comment] 2020-02-20 21:38
Argh, timer(100) still required :(

**Comment by josex2r** [comment] 2020-02-21 07:23
Sorry but I doesn't know how Angular build works :S
I'm going to close the issue, is not a bug from this lib.

**Closed by josex2r** 2020-02-21 07:23 UTC

**Comment by pacc-27** [comment] 2020-11-05 19:01
Hi!
I worked use this code in Angular and I solved this issuse for `ng build prod` change config in `angular.json`
Change it this lines:
`"configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                }
              ],
              "serviceWorker": true,
              "ngswConfigPath": "ngsw-config.json"
            }
          }`

For this:
"configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": false,
              "outputHashing": "all",
              "sourceMap": true,
              "extractCss": true,
              "namedChunks": true,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": true,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                }
              ],
              "serviceWorker": true,
              "ngswConfigPath": "ngsw-config.json"
            }
          }
        },

I not sure for why but its works for me :)
